server:
  port: 5081

spring:
  datasource:
    # Conectar al contenedor SQL Server desde Docker
    url: jdbc:sqlserver://sqlserver2022:1433;databaseName=MarcadorBasket;encrypt=false;trustServerCertificate=true
    username: sa
    password: C*123.a+
  jpa:
    hibernate:
      ddl-auto: none   # no toques el esquema por ahora
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: warn
