server:
  port: 5081

spring:
  datasource:
    # CAMBIA ESTA LÍNEA: usa localhost en lugar de sqlserver2022
    url: jdbc:sqlserver://localhost:1433;databaseName=MarcadorBasket;encrypt=false;trustServerCertificate=true
    username: sa
    password: C*123.a+
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: warn